# Generated by Django 6.0.2 on 2026-02-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Formato: YYYY-MM-DD HH:MM:SS', verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotada', 'Agotada'), ('cancelada', 'Cancelada'), ('proximamente', 'Próximamente')], default='disponible', help_text='Estado actual de la función', max_length=20, verbose_name='Estado')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la entrada en soles (S/)', max_digits=6, verbose_name='Precio')),
                ('pelicula', models.ForeignKey(help_text='Seleccione la película para esta función', on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='peliculas.pelicula', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funciones',
                'ordering': ['fecha_hora'],
                'unique_together': {('pelicula', 'fecha_hora')},
            },
        ),
    ]
