# Generated by Django 6.0.2 on 2026-02-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la entrada (ej: ENT-001-2024)', max_length=50, unique=True, verbose_name='Código')),
                ('asiento', models.CharField(help_text='Número de asiento (ej: A1, B12, C5)', max_length=10, verbose_name='Asiento')),
                ('vendido', models.BooleanField(default=False, help_text='Indica si la entrada ya fue vendida', verbose_name='Vendido')),
                ('fecha_venta', models.DateTimeField(blank=True, help_text='Fecha y hora en que se vendió la entrada (solo si está vendida)', null=True, verbose_name='Fecha de Venta')),
                ('funcion', models.ForeignKey(help_text='Función a la que pertenece esta entrada', on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='funciones.funcion', verbose_name='Función')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entradas',
                'ordering': ['funcion', 'asiento'],
                'unique_together': {('funcion', 'asiento')},
            },
        ),
    ]
