# Generated by Django 6.0.2 on 2026-02-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Nombre del producto (ej: Combo 1, Canchita Grande, Gaseosa)', max_length=100, verbose_name='Producto')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad disponible en stock', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad en soles (S/)', max_digits=6, verbose_name='Precio Unitario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('entrada', models.ForeignKey(blank=True, help_text='Entrada a la que está asociado este snack (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snacks', to='entradas.entrada', verbose_name='Entrada asociada')),
            ],
            options={
                'verbose_name': 'Snack',
                'verbose_name_plural': 'Snacks',
                'db_table': 'snacks',
                'ordering': ['producto'],
            },
        ),
    ]
